bufferapp/buffer-analyze

- Jenkinsfile
- Jenkinsfile.json
- buffer-analyze/.helmignore
- buffer-analyze/Chart.yaml
- buffer-analyze/templates/NOTES.txt
- buffer-analyze/templates/_helpers.tpl
- buffer-analyze/templates/deployment.yaml
- buffer-analyze/templates/ingress.yaml
- buffer-analyze/templates/service.yaml
- buffer-analyze/values.yaml
- pre-build.sh
- production.yaml
> Deploy files for Analyze

- package.json
- packages/server/webpack.config.js
> Add .less & CSS modules support for webpack

- .gitignore
- package.json
Speed up bootstrap process by adding a `--hoist` flag on `lerna bootstrap`.
> Speed up bootstrap process

- packages/nav-sidebar/components/Item.jsx
- packages/nav-sidebar/components/story.jsx
- packages/nav-sidebar/index.js
- packages/store/index.js
- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/DefaultPage/index.jsx
To add navigation inside the app when clicking on the links in the NavSidebar package.
> Add navigation

- packages/server/index.js
- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/App/index.jsx
- packages/web/components/ReportsPage/index.jsx
- packages/web/components/ReportsPage/story.jsx
To add a placeholder for the reports page.
> Add placeholder for the reports page

- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/App/index.jsx
- packages/web/components/ComparisonsPage/index.jsx
- packages/web/components/ComparisonsPage/story.jsx
- packages/web/components/InsightsPage/index.jsx
- packages/web/components/InsightsPage/story.jsx
- adds Comparison page placeholder
- adds Insights page placeholder
Not much to review in here Mike, it's basically a copy of the placeholder you made for the Report page :smile: 
> Add Comparison and Insights page placeholders

- .editorconfig
- packages/nav-sidebar/components/Item.jsx
- packages/nav-sidebar/components/Label.jsx
- packages/server/index.html
To add a root font size so that we can use correct rem styling.
> Add root font size

- README.md
> Add codecov.io badge

- packages/profile-loader/__snapshots__/snapshot.test.js.snap
- packages/profile-loader/components/ProfileLoader/index.jsx
- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/InsightsPage/index.jsx
Keep sidebar and tabs fixed and just allow the tab content to scroll
when it overflows the window height.
> Fix scroll

- packages/hourly-chart/__snapshots__/snapshot.test.js.snap
- packages/store/package.json
- packages/tabs/package.json
- packages/web/components/App/story.jsx
- packages/web/components/ComparisonsPage/story.jsx
- packages/web/components/InsightsPage/index.jsx
- packages/web/components/InsightsPage/story.jsx
- packages/web/components/ReportsPage/story.jsx
- packages/web/index.jsx
- packages/web/package.json
Prepend several package names with `analyze-` to ensure we don't have any name collision with buffer-publish.
> Update package names

- packages/average-table/__snapshots__/snapshot.test.js.snap
- packages/average-table/components/AverageTable/index.jsx
- packages/average-table/components/AverageTable/story.jsx
- packages/average-table/index.js
- packages/average-table/index.test.jsx
- packages/average-table/package.json
- packages/average-table/snapshot.test.js
- packages/report/components/ChartFactory/index.jsx
- packages/report/package.json
- packages/server/rpc/getReport/index.js
- packages/web/__snapshots__/snapshot.test.js.snap
Add `average-table` package support for being added to a report, and rendered in it.
> Add average-table to report

- packages/server/rpc/summary/index.js
- packages/server/rpc/summary/index.test.js
- packages/summary-table/middleware.js
- packages/summary-table/middleware.test.js
This reverts commit af719d13f21ab49696f3fa0c8e563474c08165fd,
as it has been pushed into master by mistake
> Revert "make Summary aware of profileService"

- packages/add-report/__snapshots__/snapshot.test.js.snap
- packages/report-list/components/Report/index.jsx
- packages/report-list/middleware.test.js
Fix report-list `small` prop application on Date component.
> Report list small date

- packages/contextual-compare/components/ContextualCompare/index.jsx
To show the contextual compare when  yesterday is selected as the time period
> show contextual compare for yesterday

- packages/report/__snapshots__/snapshot.test.js.snap
- packages/report/components/EditTitle/index.jsx
- packages/report/components/Report/index.jsx
- packages/report/components/Report/story.jsx
- packages/report/index.js
- packages/report/index.test.jsx
- packages/report/middleware.js
- packages/report/middleware.test.js
- packages/report/reducer.js
- packages/report/reducer.test.js
- packages/server/rpc/index.js
- packages/server/rpc/saveReportChanges/index.js
- packages/server/rpc/saveReportChanges/index.test.js
- packages/web/__snapshots__/snapshot.test.js.snap
To allow users to edit the report name by clicking on it.
There is a code coverage decrease caused by EditTitle and it's onBlur/onChange handlers. I'll investigate a good way to cover those methods in a further PR, but my confidence is high on them being good enough right now since they're just doing a single call to another (tested) method.
> Edit report name

- packages/report-list/reducer.js
- packages/report-list/reducer.test.js
- packages/server/rpc/createReport/index.js
- packages/server/rpc/createReport/index.test.js
- packages/web/__snapshots__/snapshot.test.js.snap
To ensure our report list is up to date whenever we create a new report successfully.
> New report is added to the reports collection right after being created

- packages/contextual-compare/components/Chart/index.jsx
- packages/contextual-compare/components/ContextualCompare/index.jsx
- packages/contextual-compare/index.js
- packages/contextual-compare/package.json
- packages/contextual-compare/reducer.js
- packages/contextual-compare/reducer.test.js
- packages/contextual-compare/snapshot.test.js
- packages/hourly-chart/__snapshots__/snapshot.test.js.snap
- packages/hourly-chart/components/HourlyChart/index.jsx
- packages/report/__snapshots__/snapshot.test.js.snap
- packages/report/components/ChartFactory/index.jsx
- packages/report/package.json
- packages/server/rpc/contextual/index.js
- packages/server/rpc/contextual/index.test.js
- packages/server/rpc/getReport/index.js
- packages/server/rpc/getReport/index.test.js
To allow Contextual Comparison charts to be added to reports.
> Add contextual compare to report

- packages/average-table/components/AverageTable/index.jsx
- packages/compare-chart/components/Chart/index.jsx
- packages/compare-chart/components/CompareChart/index.jsx
- packages/compare-chart/components/CompareChart/story.jsx
- packages/compare-chart/index.js
- packages/compare-chart/index.test.jsx
- packages/compare-chart/package.json
- packages/compare-chart/snapshot.test.js
- packages/report/components/ChartFactory/index.jsx
- packages/report/package.json
- packages/server/rpc/getReport/index.js
To allow the metrics breakdown charts to be rendered in reports.
I had to push some logic inside the `Chart` component so that we are able to handle its data when rendering from a report. Would love your thoughts @federicoweber!
> Add metrics breakdown chart to reports

- packages/server/rpc/createReport/index.js
- packages/server/rpc/createReport/index.test.js
Return `Date.now()` as `updated_at` when a report has been created
> Fix creation date for reports

- packages/report/middleware.js
- packages/report/middleware.test.js
- packages/server/rpc/getReport/index.js
- packages/server/rpc/summary/index.js
- packages/server/rpc/summary/index.test.js
- packages/summary-table/__snapshots__/snapshot.test.js.snap
- packages/summary-table/components/SummaryTable/index.jsx
- packages/summary-table/components/SummaryTable/story.jsx
- packages/summary-table/middleware.js
- packages/summary-table/middleware.test.js
- packages/summary-table/package.json
- yarn.lock
> [WIP] Instagram overview Summary

- packages/report/middleware.js
- packages/report/middleware.test.js
- packages/report/reducer.js
- packages/report/reducer.test.js
- packages/server/rpc/deleteChart/index.js
- packages/server/rpc/deleteChart/index.test.js
- packages/server/rpc/index.js
To be able to remove a chart from a report.
> Remove chart from report

- README.md
- package.json
- packages/server/index.js
- packages/server/webpack.config.dev.js
- packages/server/webpack.config.js
- packages/web/index.jsx
- yarn.lock
To improve dev experience by moving webpack bundling outside the container and fixing HMR.
To make sure you have the last version of the devtools installed, please run:
`rm -rf node_modules && yarn run clean && yarn`
After that, just remember to have always `yarn watch` running while coding :)
> Improve dev experience 💻✨

- packages/hourly-chart/__snapshots__/snapshot.test.js.snap
- packages/hourly-chart/components/ChartHeader/index.jsx
- packages/hourly-chart/components/Legend/index.jsx
- packages/hourly-chart/components/TimezoneInfo/index.jsx
Some styling and component updates plus some refactoring which help complete this task: https://app.getflow.com/organizations/369191/teams/339227/tasks/28535374
Trying to keep this nice and small for review 😄 
Be awesome if either @msanroman or @tiggreen could look at this 👍 
https://task-chart-styling-updates-analyze.dev.buffer.com/ :smile:_
> Hourly engagement chart styling updates

- packages/pdf-export/__snapshots__/snapshot.test.js.snap
- packages/pdf-export/components/PDFExportButton/index.jsx
- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/ReportsPage/index.jsx
To fix the styling of the Export as PDF button and keep it consistent with the rest of the UI.
> Fix styling for the "Export as PDF" button

- packages/report/__snapshots__/snapshot.test.js.snap
- packages/report/components/ChartFactory/index.jsx
- packages/report/components/Report/story.jsx
- packages/web/__snapshots__/snapshot.test.js.snap
To make clearer for which profile does each module belong to in a report.
> Show profile badge with avatar/social icon on "Showing for accounts" legend

- packages/audience-chart/__snapshots__/snapshot.test.js.snap
- packages/audience-chart/components/Title/index.jsx
- packages/average-table/__snapshots__/snapshot.test.js.snap
- packages/average-table/components/AverageTable/index.jsx
- packages/contextual-compare/__snapshots__/snapshot.test.js.snap
- packages/contextual-compare/components/Title/index.jsx
- packages/hourly-chart/__snapshots__/snapshot.test.js.snap
- packages/hourly-chart/components/HourlyChart/index.jsx
- packages/posts-table/index.jsx
- packages/shared-components/PostsTable/components/Title/index.jsx
- packages/shared-components/PostsTable/index.jsx
- packages/shared-components/PostsTable/story.jsx
- packages/shared-components/PostsTable/styles.less
- packages/shared-components/__snapshots__/snapshot.test.js.snap
- packages/top-posts-table/index.jsx
- packages/web/components/OverviewTab/index.jsx
- packages/web/components/OverviewTab/index.test.jsx
This has style updates to the new Posts table and visually removed the old Top Posts. It also includes some text updates to make the graph headers more consistent.
This is a fresh pull request which has cherry-picked commits to make the merge to master much easier. @federicoweber will know about this 😉 I haven't removed the older top posts component as I was concerned about the knock-on effects. I've discussed this with @federicoweber and he'll do that in a separate pull request 👍 
It'd be great @federicoweber if you could take a look at this one.
https://task-post-table-updates-analyze.dev.buffer.com :smile:_
> Post table updates

- packages/nav-sidebar/__snapshots__/snapshot.test.js.snap
- packages/nav-sidebar/components/Insights.jsx
- packages/nav-sidebar/components/story.jsx
- packages/nav-sidebar/index.js
- packages/nav-sidebar/index.test.jsx
- packages/nav-sidebar/reducer.js
- packages/nav-sidebar/reducer.test.js
- packages/nav-sidebar/snapshot.test.js
- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/App/story.jsx
- packages/web/components/DefaultPage/index.jsx
Replace "You are logged in!" message with something simple but useful:
> Replace "logged in" message with simple dashboard

- packages/add-report/__snapshots__/snapshot.test.js.snap
- packages/audience-chart/__snapshots__/snapshot.test.js.snap
- packages/audience-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/average-table/__snapshots__/snapshot.test.js.snap
- packages/comments-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/__snapshots__/snapshot.test.js.snap
- packages/contextual-compare/__snapshots__/snapshot.test.js.snap
- packages/engagement-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/hourly-chart/__snapshots__/snapshot.test.js.snap
- packages/likes-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/posts-summary-table/__snapshots__/snapshot.test.js.snap
- packages/reach-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/report-list/__snapshots__/snapshot.test.js.snap
- packages/report-list/components/RemoveButton/index.jsx
- packages/report-list/components/RemoveButton/story.jsx
- packages/report-list/components/Report/RemovableReport.jsx
- packages/report-list/components/ReportList/index.jsx
- packages/report-list/components/ReportText/index.jsx
- packages/report/__snapshots__/snapshot.test.js.snap
- packages/report/components/ChartEditButtons/index.jsx
- packages/report/components/EditTitle/index.jsx
- packages/report/components/Report/index.jsx
- packages/shared-components/ChartStateLoading/index.jsx
- packages/shared-components/__snapshots__/snapshot.test.js.snap
- packages/summary-table/__snapshots__/snapshot.test.js.snap
- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/ReportsList/index.jsx
- packages/web/components/ReportsPage/index.jsx
I was just trying to tackle the hover title edit task but decided to try and fix a few other little things here, such as stopping the sidebar from changing sizes when in reports compared to other pages of the app, fixing the toolbar to look right on the report page, a nicer back to reports button, making the whole report item clickable to open rather than the view report button, nicer looking loading for the list and report.
https://task-small-report-updates-analyze.dev.buffer.com/ :smile:_
> Small report updates

- packages/add-report/components/AddReport/index.jsx
- packages/add-report/components/AddReport/story.jsx
- packages/add-report/components/Modal/index.jsx
- packages/add-report/components/Modal/story.jsx
- packages/add-report/mock/reports.js
- packages/audience-comparison-chart/components/AudienceComparisonChart/index.jsx
- packages/average-table/components/AverageTable/index.jsx
- packages/report-list/components/Date/index.jsx
- packages/report-list/components/Report/SelectableReport.jsx
- packages/shared-components/ChartStateNoData/index.jsx
- packages/shared-components/ComparisonChartWrapper/index.jsx
- packages/shared-components/ComparisonFooter/index.jsx
- packages/shared-components/GridItem/components/GridItemChart/index.jsx
- packages/shared-components/GridItem/index.jsx
to clean up console warnings both in the browser and in tests
It takes care of the following components:
- add-report
- NoData
- Audience Comparison
- Average Table
> Cleanup Components props

- packages/server/index.js
> Add dd-agent host

- packages/early-access-check/.babelrc
- packages/early-access-check/.storybook/addons.js
- packages/early-access-check/.storybook/config.js
- packages/early-access-check/.storybook/preview-head.html
- packages/early-access-check/.storybook/webpack.config.js
- packages/early-access-check/README.md
- packages/early-access-check/index.js
- packages/early-access-check/index.test.jsx
- packages/early-access-check/middleware.js
- packages/early-access-check/middleware.test.js
- packages/early-access-check/package.json
- packages/server/rpc/utils/parseUser.js
- packages/store/index.js
- packages/store/package.json
Ensure that only users with the `analyze_early_access` feature flip have access to Analyze.
> Add feature flip check

- packages/performance-tracking/middleware.js
> small style refactor performance middleware

- packages/png-export/lib/generatePNGFromChart.js
- packages/png-export/lib/generatePNGFromChart.test.js
- packages/png-export/package.json
- packages/posts-table/__snapshots__/snapshot.test.js.snap
- packages/posts-table/components/PostsTable/components/PostItem/index.jsx
- yarn.lock
To ensure exported images have the highest quality.
> Render PNGs at 300dpi

- packages/server/rpc/comparison/index.js
- packages/server/rpc/comparison/mockResponse.js
We should have different colors for each profile in Comparisons page.
Here is the [JIRA story](https://buffer.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=BAN&modal=detail&selectedIssue=BAN-56).
> Comparison Charts: Ensure colors are always different

- packages/audience-chart/__snapshots__/snapshot.test.js.snap
- packages/audience-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/comments-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/components/CompareChart/index.jsx
- packages/contextual-compare/__snapshots__/snapshot.test.js.snap
- packages/engagement-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/likes-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/reach-comparison-chart/__snapshots__/snapshot.test.js.snap
- packages/shared-components/CommonChart/index.jsx
- packages/shared-components/ComparisonChart/index.jsx
- packages/shared-components/__snapshots__/snapshot.test.js.snap
this will prevent scrolling when changing the data in some browsers
BAN-47
> ensure minHeight to charts

- packages/compare-chart/components/Chart/index.jsx
- packages/shared-components/CommonChart/index.jsx
- packages/shared-components/ComparisonChart/index.jsx
This adjusts the gradient of the charts so they're not so severe.
This changes the gradients of columns and series.
Would love to get your eyes on this @federicoweber!
http://task-change-gradient-for-charts-analyze.dev.buffer.com/ :smile:_
> Little adjustments to gradient for visual calmness

- packages/compare-chart/components/Chart/chartConfig.jsx
- packages/compare-chart/components/Chart/index.jsx
- packages/server/index.js
- packages/shared-components/CommonChart/chartConfig.jsx
- packages/shared-components/CommonChart/index.jsx
To fix chart scales in report exports.
> Fix report rendering

- packages/multi-profile-selector/__snapshots__/snapshot.test.js.snap
- packages/multi-profile-selector/components/MultiProfileSelector/index.jsx
- packages/multi-profile-selector/components/MultiProfileSelector/story.jsx
… two or more profiles are selected.
> Multi-Profile Picker: Compare Profiles button should only enable when two or more profiles are selected.

- packages/multi-profile-selector/__snapshots__/snapshot.test.js.snap
- packages/multi-profile-selector/components/MultiProfileSelector/index.jsx
- packages/multi-profile-selector/components/MultiProfileSelector/story.jsx
- packages/shared-components/DropdownItem/index.jsx
- packages/shared-components/DropdownItem/story.jsx
- packages/shared-components/DropdownItem/style.less
Here is the [JIRA card](https://buffer.atlassian.net/secure/RapidBoard.jspa?rapidView=17&modal=detail&selectedIssue=BAN-62) for more details.
> Multi-Profile Picker: When 5 profiles are selected, we should dim/disable clicking on more than 5 profiles

- packages/compare-chart/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/components/CompareChart/index.jsx
- packages/compare-chart/index.js
add the footer on export and reports for Metrics Breakdown chart 
fixes BAN-101
> add Metrics Breakdown footer on export and reports

- packages/date-picker/__snapshots__/snapshot.test.js.snap
- packages/date-picker/components/DatePicker/Presets.jsx
- packages/shared-components/__snapshots__/snapshot.test.js.snap
- packages/web/__snapshots__/snapshot.test.js.snap
This fixes the date preset buttons so the whole button is clickable by the user. It relates to this JIRA task: https://buffer.atlassian.net/browse/BAN-85
https://task-update-date-preset-buttons-analyze.dev.buffer.com :smile:_
> Update date preset buttons

- packages/compare-chart/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/components/ChartTooltip/index.jsx
- packages/shared-components/CommonChart/components/ChartTooltip/index.jsx
- packages/shared-components/ComparisonChartTooltip/index.jsx
- packages/shared-components/__snapshots__/snapshot.test.js.snap
Super small one to fix dates in the tooltips to make them small rather than extra small. This relates to this JIRA ticket: https://buffer.atlassian.net/browse/BAN-104
https://task-tooltips-too-small-analyze.dev.buffer.com :smile:_
> Tooltip date text updates

- packages/date-picker/__snapshots__/snapshot.test.js.snap
- packages/date-picker/components/DatePicker/Month.jsx
- packages/date-picker/components/DatePicker/story.jsx
To ensure that Reports and Comparison can use the "custom" date picker.
> Make custom DatePicker available for non single profile views

- packages/multi-profile-selector/reducer.js
- packages/multi-profile-selector/reducer.test.js
- packages/web/components/ComparisonsPage/index.jsx
Here is the [JIRA card](https://buffer.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=BAN&modal=detail&selectedIssue=BAN-63) for more context. 
> Multi-Profile Picker: Selecting a profile should not trigger the chart become visible

- packages/comparison_chart/__snapshots__/snapshot.test.js.snap
- packages/comparison_chart/components/Chart/index.jsx
- packages/comparison_chart/components/ChartTooltip/index.jsx
- packages/comparison_chart/components/ChartTooltip/story.jsx
- packages/comparison_chart/components/ChartWrapper/story.jsx
- packages/server/rpc/comparison/index.js
- packages/server/rpc/comparison/mockResponse.js
To differentiate between the cases where a metric is 0 when no followers have interacted with the content and when it's 0 because no content has been shared on a given day.
BAN-113
> Add zeroes and tooltips for missing data in Comparisons

- packages/compare-chart/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/components/CompareChart/index.jsx
- packages/shared-components/CommonChart/index.jsx
- packages/shared-components/CommonChart/story.jsx
- packages/shared-components/__snapshots__/snapshot.test.js.snap
Move the "no data" message inside the exported components for compare chart and the common chart component in reports.
> Fix reports not loading

- packages/server/rpc/comparison/index.js
- packages/server/rpc/comparison/index.test.js
- packages/server/rpc/comparison/mockResponse.js
- packages/server/rpc/utils/DateRange.js
- packages/server/rpc/utils/DateRange.test.js
To display all the days in the select range in the charts even if we have data for just a few of those.
> comparisons always show all the days in range BAN-113

- packages/nav-sidebar/__snapshots__/snapshot.test.js.snap
- packages/nav-sidebar/components/NavSidebar.jsx
- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/DefaultPage/index.jsx
To rollout `/comparisons` to all users!
> Rollout comparison

- packages/report-list/__snapshots__/snapshot.test.js.snap
- packages/report-list/components/Date/index.jsx
- packages/report-list/components/Report/RemovableReport.jsx
- packages/report-list/components/ReportList/story.jsx
> fix title dates in reports list

- packages/server/rpc/compare/index.test.js
- packages/server/rpc/compare/metricsConfig.js
Here is the [JIRA card.](https://buffer.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=BAN&modal=detail&selectedIssue=BAN-138)
> Change Metrics Breakdown default metric to "Total Followers"

- packages/date-picker/middleware.js
- packages/date-picker/middleware.test.js
- packages/date-picker/reducer.js
- packages/date-picker/reducer.test.js
As a user, I want my selected date ranges to remain selected when I navigate around Analyze so I can quickly switch between tabs, not be surprised by changing data, and save time by not having to constantly re-select dates.
> Persist date for tabs BAN-79

- packages/hourly-chart/__snapshots__/snapshot.test.js.snap
- packages/hourly-chart/components/Dropdown/List.jsx
- packages/hourly-chart/components/Dropdown/index.jsx
To make the hourly chart more consistent with the rest of the UI.
> Dropdown labels for hourly chart should be circles

- packages/web/components/InsightsPage/index.jsx
To fix [BAN-184](https://buffer.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=BAN&modal=detail&selectedIssue=BAN-184)
> [BAN-184] Fix profile dropdown z positioning

- packages/add-report/__snapshots__/snapshot.test.js.snap
- packages/audience-chart/__snapshots__/snapshot.test.js.snap
- packages/average-table/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/__snapshots__/snapshot.test.js.snap
- packages/comparison_chart/__snapshots__/snapshot.test.js.snap
- packages/contextual-compare/__snapshots__/snapshot.test.js.snap
- packages/pdf-export/__snapshots__/snapshot.test.js.snap
- packages/posts-summary-table/__snapshots__/snapshot.test.js.snap
- packages/report-list/__snapshots__/snapshot.test.js.snap
- packages/report/__snapshots__/snapshot.test.js.snap
- packages/shared-components/Toolbar/index.jsx
- packages/shared-components/__snapshots__/snapshot.test.js.snap
- packages/shared-components/index.js
- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/ComparisonsPage/index.jsx
- packages/web/components/InsightsPage/index.jsx
Make toolbar height consistent by creating a Toolbar component.
> Fix toolbar height inconsistencies

- packages/compare-chart/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/components/Title/index.jsx
- packages/compare-chart/components/Title/story.jsx
Title for compare chart on a report is the selected metric label.
> [BAN-125] Improve title of "Metrics Breakdown" when on Reports

- packages/posts-table/__snapshots__/snapshot.test.js.snap
- packages/posts-table/components/PostsTable/metrics.js
To allow users sort the posts in the posts table by date for all networks.
> [ANA-185] Add "Sort by date" on top posts table

- packages/server/rpc/average/index.js
- packages/server/rpc/average/index.test.js
To have clearer labels on the average chart so that it is self-explanatory :)
> [ANA-11] Add clearer average chart headings

- packages/server/rpc/summary/index.js
- packages/summary-table/__snapshots__/snapshot.test.js.snap
- packages/summary-table/components/SummaryTable/index.jsx
- packages/summary-table/components/SummaryTable/story.jsx
Instagram Performance table now shows this metrics:
- Posts
- Impressions
- Reach
- Likes
- Comments
- New Followers
> update Instagram performance table metrics (ANA-153)

- packages/posts-table/__snapshots__/snapshot.test.js.snap
- packages/posts-table/components/PostsTable/metrics.js
- packages/server/rpc/compare/metricsConfig.js
To add Engagement Rate for the following Twitter Charts:
- Metrics Breakdown
- Tweet breakdown
> Twitter Engagement Rate (ANA-197)

- packages/average-table/__snapshots__/snapshot.test.js.snap
- packages/average-table/components/AverageTable/index.jsx
- packages/average-table/components/AverageTable/story.jsx
- packages/average-table/middleware.js
- packages/average-table/middleware.test.js
- packages/server/rpc/average/index.js
- packages/server/rpc/average/index.test.js
As a user, I want to see averages of key metrics of my business Instagram profile posts so that I can get a clearer picture of how well my content is working.
> Instagram Advanced Average Performance graph (ANA-157)

- packages/multi-profile-selector/__snapshots__/snapshot.test.js.snap
- packages/multi-profile-selector/components/MultiProfileSelector/style.less
- packages/profile-selector/__snapshots__/snapshot.test.js.snap
- packages/profile-selector/components/ProfileSelectorDropdown/index.jsx
- packages/shared-components/DropdownItem/index.jsx
- packages/shared-components/DropdownItem/story.jsx
- packages/shared-components/DropdownItem/style.less
- packages/shared-components/__snapshots__/snapshot.test.js.snap
To properly display long names in Profile selectors
> Fix/profile selector (ANA-204)

- packages/nav-sidebar/__snapshots__/snapshot.test.js.snap
- packages/nav-sidebar/components/Insights.jsx
- packages/profile-selector/middleware.js
- packages/server/rpc/contextual/metricsConfig.js
- packages/shared-components/style/index.js
- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/components/InsightsPage/index.jsx
- add profile_id in the url on answers section
- fix export name for answers
- fix Url Clicks metric parsing for Twitter
> small fixes for answers section

- packages/posts-table/__snapshots__/snapshot.test.js.snap
- packages/posts-table/components/PostsTable/components/PostsHeader/components/PostOrderSwitch/index.jsx
- packages/posts-table/components/PostsTable/components/PostsHeader/components/PostOrderSwitch/style.less
To finetune visual vertical spacing of the PostOrderSwitch
> beter visual vertical alignment of PostOrderSwitch

- packages/server/index.html
- packages/server/index.js
Hey @federicoweber, would love your eyes on this. Is this a fine way to disable FullStory? :) 
> Temporary disable FullStory.

- packages/server/rpc/getReport/index.js
- packages/server/rpc/getReport/index.test.js
To fix a bug introduced in #231 that was preventing reports from loading.
> fix get report

- packages/posts-table/components/PostsTable/styles.less
To render Posts table metrics bars when exporting to pdf
> fix post table bars in pdf reports

- packages/posts-table/__snapshots__/snapshot.test.js.snap
- packages/posts-table/components/PostsTable/components/PostItem/index.jsx
- packages/posts-table/components/PostsTable/index.jsx
- packages/posts-table/components/PostsTable/story.jsx
- packages/report/components/ChartFactory/index.jsx
To hide the view post link, in the Posts Table, from the exported pdf.
> post-table remove view post url on export (ANA-246)

- buffer-analyze/templates/deployment.yaml
> Revert helm deployment

- packages/early-access-check/middleware.js
To make sure we are redirecting unenrolled users to the welcome page.
> fixes the redirect for unenrolled users

- packages/report/__snapshots__/snapshot.test.js.snap
- packages/report/components/Cover/index.jsx
- packages/report/components/Cover/story.jsx
- packages/report/components/EditDescription/index.jsx
- packages/report/components/EditDescription/index.test.jsx
- packages/report/components/EditDescription/story.jsx
- packages/report/components/Report/index.jsx
- packages/report/components/Report/story.jsx
- packages/report/index.js
- packages/report/index.test.jsx
- packages/report/middleware.js
- packages/report/middleware.test.js
- packages/report/reducer.js
- packages/report/reducer.test.js
- packages/server/rpc/saveReportChanges/index.js
- packages/server/rpc/saveReportChanges/index.test.js
- packages/web/__snapshots__/snapshot.test.js.snap
Here is the [JIRA card](https://buffer.atlassian.net/browse/ANA-24) for more context.
> [ANA-24] Reports should have an optional editable description

- packages/posts-table/__snapshots__/snapshot.test.js.snap
- packages/posts-table/components/PostsTable/components/PostItem/index.jsx
To prevent some rows to go wider than they should and their attachment taller than the row:
> Fix posts table layout

- packages/profile-overview/__snapshots__/snapshot.test.js.snap
- packages/profile-overview/components/ProfilesTable/components/ProfileItem/index.jsx
- packages/profile-overview/components/ProfilesTable/index.jsx
- packages/profile-overview/components/ProfilesTable/story.jsx
To show Engagement rate in profiles overview (ANA-254)
> Switch engagement with eng. rate profiles overview  (ANA-254)

- packages/add-report/middleware.js
- packages/add-report/middleware.test.js
- packages/profile-selector/mocks/profiles.js
- packages/profile-selector/reducer.js
- packages/profile-selector/reducer.test.js
- packages/server/rpc/createReport/index.js
- packages/server/rpc/utils/profileParser.js
To store reports based on organization ID rather than user ID.
> [ANA-269] Store organization ID from profile list and send it when creating reports

- packages/csv-export/middleware.js
- packages/csv-export/middleware.test.js
This enables csv export button after export.
> fix csv export button (ANA-310)

- packages/posts-table/__snapshots__/snapshot.test.js.snap
- packages/posts-table/components/PostsTable/components/PostItem/index.jsx
- packages/server/index.js
To allow reports bigger than 6MB to be downloaded as PDF too.
I'll switch to the non `Dev` branch of the Lambda function once I've uploaded its new implementation there - doing it in two phases to ensure there is no downtime on downloading reports.
> Proxy reports stored on S3

- packages/server/index.js
> Use non-dev lambda function to export to PDF

- packages/report-list/middleware.js
- packages/report-list/middleware.test.js
- packages/server/rpc/listReports/index.js
- packages/server/rpc/listReports/index.test.js
To be merged after the migration.
> List reports by organization

- packages/nav-sidebar/__snapshots__/snapshot.test.js.snap
- packages/nav-sidebar/components/TrialStatus.jsx
- packages/nav-sidebar/components/story.jsx
- packages/server/rpc/getAccountDetails/index.js
- packages/server/rpc/getAccountDetails/test.js
To fix the "in-app" trial status that is off by one day.
> Fix trial status off by one day

- helm/values.yaml
> Fixed incorrect indentation in env

- packages/posts-table/__snapshots__/snapshot.test.js.snap
- packages/posts-table/components/PostsTable/components/BreakdownLegend/index.jsx
- packages/posts-table/components/PostsTable/components/BreakdownLegend/sortingDictionary.js
- packages/posts-table/components/PostsTable/components/BreakdownLegend/story.jsx
- packages/posts-table/components/PostsTable/components/PostItem/index.jsx
- packages/posts-table/components/PostsTable/components/PostsHeader/index.jsx
- packages/posts-table/components/PostsTable/components/Searchbox/index.jsx
- packages/posts-table/components/PostsTable/index.jsx
- packages/posts-table/components/PostsTable/story.jsx
- packages/posts-table/index.jsx
- packages/posts-table/index.test.jsx
- packages/posts-table/middleware.js
- packages/posts-table/middleware.test.js
- packages/posts-table/package.json
- packages/posts-table/reducer.js
- packages/posts-table/reducer.test.js
- packages/report/__snapshots__/snapshot.test.js.snap
- packages/report/components/ChartFactory/index.jsx
- packages/server/rpc/getReport/index.js
- packages/server/rpc/posts/index.js
- packages/server/rpc/posts/index.test.js
- packages/shared-components/ChartStateNoData/index.jsx
- packages/web/__snapshots__/snapshot.test.js.snap
- yarn.lock
To be able to filter the post breakdown table by different keywords, and store that search in a report.
Even though codecov is complaining, I think we're good as the number of lines in the codebase has increased and the coverage diff is just -0.02% :)
> Filter posts

- packages/add-report/__snapshots__/snapshot.test.js.snap
- packages/audience-chart/__snapshots__/snapshot.test.js.snap
- packages/average-table/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/__snapshots__/snapshot.test.js.snap
- packages/comparison_chart/__snapshots__/snapshot.test.js.snap
- packages/contextual-compare/__snapshots__/snapshot.test.js.snap
- packages/hashtags-table/__snapshots__/snapshot.test.js.snap
- packages/hourly-chart/__snapshots__/snapshot.test.js.snap
- packages/posts-summary-table/__snapshots__/snapshot.test.js.snap
- packages/posts-table/__snapshots__/snapshot.test.js.snap
- packages/profile-overview/__snapshots__/snapshot.test.js.snap
- packages/report-list/__snapshots__/snapshot.test.js.snap
- packages/report/__snapshots__/snapshot.test.js.snap
- packages/report/components/ChartFactory/index.jsx
- packages/rpc-worker/.index.js@neomake_26638_268.js
- packages/rpc-worker/.index.test.js@neomake_26638_269.js
- packages/shared-components/ChartCard/index.jsx
- packages/shared-components/ErrorBoundary/index.jsx
- packages/shared-components/ErrorBoundary/story.jsx
- packages/shared-components/__snapshots__/snapshot.test.js.snap
- packages/shared-components/index.js
- packages/summary-table/__snapshots__/snapshot.test.js.snap
- packages/web/.rpcWorker.js@neomake_26638_267.js
To catch an error in any of our charts and show an error state instead of crashing the entire app.
Down the line we can extend the error handling to log errors, for now, I just want to prevent Analyze from crashing for a single faulty component :wink:.
> add ErrorBoundary component

- packages/compare-chart/__snapshots__/snapshot.test.js.snap
- packages/compare-chart/components/CompareChart/index.jsx
To fix empty Metrics Breakdown chart
> Fix Empty Metrics Breakdown

- packages/web/__snapshots__/snapshot.test.js.snap
- packages/web/package.json
- yarn.lock
To remove the coming soon message if a user has access to Analyze.
> update App Sidebar
