buffer-analyze/values.yaml
This PR should install the updated ssl crt that includes `analyze.buffer.com` to its production ELB
=> Use the new ssl CRT that includes analyze.buffer.com

package.json, packages/i18n/package.json, packages/nav-sidebar/package.json, packages/performance-tracking/package.json, packages/profile-selector/package.json, packages/server/package.json, packages/store/package.json, packages/summary-table/package.json, packages/web/package.json
To speed up project wide testing, this will lint `.js` and `.jsx` files
that have been edited in the current branch (both committed and not).
Doing some test this reduced the testing time from **28s** to **19s** _( time will vary based on the number of files to lint, but it should be faster than linting it all :smile: )_.
To fully lint individual package you should run `yarn run lint` from the package directory.
As ESlint uses stdout, this won't run the tests if there is a linting error, if you just want to run the tests you can use `lerna run test`
=> Faster project wide linting

packages/nav-sidebar/middleware.js, packages/nav-sidebar/middleware.test.js, packages/profile-loader/index.js, packages/profile-loader/index.test.jsx, packages/profile-loader/middleware.js, packages/profile-loader/middleware.test.js, packages/store/index.js
@federicoweber made a really good point that the logic place for the profile fetching to be triggered would be the middleware for the profile-loader package, since that's also the package that prevents UI elements from being rendered until there are profiles available.
This PR takes care of that move 😄
=> Handle profile fetching after login with profile-loader

packages/performance-tracking/index.js, packages/performance-tracking/middleware.js, packages/performance-tracking/middleware.test.js, packages/performance-tracking/reducer.js, packages/performance-tracking/reducer.test.js
to ensure we are tracking performances for all RPC endpoints, we are now tracking all async data fetch request automatically.
To keep the middleware cases declarations Redux friendly, this is using `RegExp.test` method instead of passing the type variable as a `switch` argument.
=> Automatic async data fetch performance tracking

packages/date-picker/__snapshots__/snapshot.test.js.snap, packages/date-picker/components/DatePicker/index.jsx
This prevents the Profile Selector drop-down opening at the same time as the date picker.
=> fix datepicker and profile selector overlap

packages/hourly-chart/components/HourlyEngagementChart/index.jsx, packages/hourly-chart/components/PostCountByHour/index.jsx
To _really_ set the timezone offset for the HourlyEngagements chart 😄. Thanks @federicoweber for noticing that!
=> Move getTimezoneOffset to Highcharts.global

packages/posts-summary-table/__snapshots__/snapshot.test.js.snap, packages/posts-summary-table/components/PostsSummaryTable/index.jsx, packages/posts-summary-table/components/Title/index.jsx, packages/posts-summary-table/index.js, packages/posts-summary-table/index.test.jsx, packages/posts-summary-table/package.json, packages/posts-summary-table/snapshot.test.js, packages/report/__snapshots__/snapshot.test.js.snap, packages/report/components/ChartFactory/index.jsx, packages/report/package.json, packages/server/rpc/getReport/index.js, packages/shared-components/ChartHeader/index.jsx, packages/shared-components/index.js, packages/summary-table/__snapshots__/snapshot.test.js.snap, packages/summary-table/components/SummaryTable/index.jsx, packages/web/__snapshots__/snapshot.test.js.snap, packages/web/components/ReportsPage/story.jsx, yarn.lock
To add "posts-summary-table" support for reports. Creating a report with the posts-summary-table package, and viewing it, works as expected.
=> Add posts summary table to report detail

packages/server/rpc/contextual/presets.js
To fix the missing metrics list from the Content Type preset tooltip
=> show metrics list on content type preset tooltip

packages/report-list/__snapshots__/snapshot.test.js.snap, packages/server/rpc/getReport/index.js, packages/server/rpc/getReport/index.test.js, packages/summary-table/__snapshots__/snapshot.test.js.snap, packages/top-posts-table/__snapshots__/snapshot.test.js.snap
Merge chart state with chart parameters on RPC endpoint with `Object.assign` rather than using the object spread syntax.
=> Fix "getReport" RPC endpoint

packages/average-table/components/AverageTable/story.jsx, packages/average-table/package.json, packages/compare-chart/components/CompareChart/story.jsx, packages/compare-chart/package.json, packages/contextual-compare/components/ContextualCompare/story.jsx, packages/contextual-compare/package.json, packages/decorators/components/ReportsStore/index.jsx, packages/decorators/index.js, packages/decorators/index.test.jsx, packages/decorators/package.json, packages/hourly-chart/components/HourlyChart/story.jsx, packages/report/__snapshots__/snapshot.test.js.snap, packages/report/components/Report/story.jsx, packages/summary-table/components/SummaryTable/story.jsx, packages/summary-table/package.json, packages/top-posts-table/package.json, packages/web/__snapshots__/snapshot.test.js.snap, packages/web/components/InsightsPage/story.jsx, packages/web/components/ReportsPage/story.jsx
To fix Storybooks for Components that require `reportList` and `i18n` stores.
Hey @msanroman working on the Summary I noticed that Storybook was complaining about a missing store; because `AddReport` is directly accessing it from the `Provider`. 
This is totally fine, and on the snapshot tests it's working great because we are mocking `AddReport`.
To make Storybook work properly in this case I've added a small decorator that wraps the story into a  `Provider ` component. 
Calling it `ReportsStore`, as of now we are using it only for that purpose but we can probably make a more generic one down the line.
If this approach is fine with you I will add the decorator to the rest of the components that are using it before merging this in.
_This repo is CI/CD enabled and staging deployment should …
=> add ReportsStore Decorator

packages/server/rpc/compare/index.js, packages/server/rpc/compare/index.test.js, packages/server/rpc/compare/metricsConfig.js, packages/server/rpc/compare/mockResponses.js, packages/web/__snapshots__/snapshot.test.js.snap, packages/web/components/OverviewTab/index.jsx, packages/web/components/OverviewTab/index.test.jsx
Uses Analyze-api endpoint to populate the Metrics Breakdown chart for Instagram.
=> add Compare chart to Instagram Overview

packages/server/index.js, packages/web/__snapshots__/snapshot.test.js.snap, packages/web/components/OverviewTab/index.test.jsx, packages/web/package.json, yarn.lock
Hey @hharnisc! Would love to get your eyes on this. After #89 Analyze got into a `crashLoopBackoff` error and it seems like it is caused by requiring `babel-polyfill` in production.
Since it's a dev dependency, I wonder if just adding it in there with the rest of webpack configuration would do the trick :)
=> Do not use babel-polyfill in production

packages/profile-selector/middleware.js, packages/profile-selector/middleware.test.js, packages/server/package.json, packages/server/rpc/performanceTracking/index.js, yarn.lock
To track performances in Data Dog independently from buffer web.
It also adds the tracking of first meaningful paint.
=> Directly send perf measures to DataDog

packages/posts-summary-table/components/PostsSummaryTable/index.jsx, packages/posts-summary-table/middleware.js, packages/profile-selector/middleware.js, packages/profile-selector/middleware.test.js, packages/server/rpc/postsSummary/index.js, packages/server/rpc/postsSummary/index.test.js
To add Upadates summary for Instagram, using Analyze-api.
This also fix a bug, where the profileService was missing, when switching social network from the navSidebar.
=> Add Instagram post-summary

packages/server/rpc/compare/index.test.js, packages/server/rpc/compare/metricsConfig.js
Related to this [flow card](https://beta.getflow.com/organizations/369191/teams/339227/tasks/27628823). 
Screenshot: 
=> Add Post Reach metric to FB compare chart

packages/date-picker/middleware.js, packages/date-picker/middleware.test.js, packages/pdf-export/middleware.js, packages/pdf-export/middleware.test.js, packages/report/middleware.js, packages/report/middleware.test.js, packages/server/index.js, packages/web/components/ReportsPage/story.jsx
To allow PDF exports of reports with date ranges different than 7 days.
If there is a date range defined as query string on the URL (generated automatically through the PDF export button middleware), we'll use it as the source of truth for defining the state of the date reducer.
=> PDF exports should respect the selected date range

packages/pdf-export/middleware.js, packages/pdf-export/middleware.test.js, packages/server/index.js
To set the report name as the name of the PDF file when exporting a report to PDF.
=> Set report name as PDF filename

packages/server/index.html, packages/server/index.js, packages/store/initMiddleware.js, packages/store/package.json, packages/web/__snapshots__/snapshot.test.js.snap, packages/web/package.json, yarn.lock
Adds FullStory session tracking:
=> Added Fullstory support

.editorconfig, .eslintrc.json, packages/compare-chart/components/Chart/index.jsx, packages/contextual-compare/components/ContextualCompare/index.jsx, packages/hourly-chart/components/HourlyChart/index.jsx, packages/hourly-chart/components/HourlyEngagementChart/index.jsx, packages/shared-components/CommonChart/index.jsx
To prevent charts from re-rendering when performing actions on the package.
By definition, the nested structures we have (mainly, the data for the chart itself) never changes for any given combination of the other props. So we can just use `PureComponent`s and use shallow comparisons. If another prop changes (like `selectedMetric`) a re-render will be caused as expected.
=> Prevent chart rerender on dropdown open

package.json
To fix `Error: Failed to load gRPC binary module because it was not installed for the current system` when running Analyze on a non-linux environment.
=> Rebuild grpc after installing everything so that it has the linux binary

packages/nav-sidebar/__snapshots__/snapshot.test.js.snap, packages/nav-sidebar/components/NavSidebar.jsx, packages/web/__snapshots__/snapshot.test.js.snap
To temporarily hide the Comparison tool from the sidebar.
Hey, @tomredman just want to confirm that we only want to remove the button and have the tool accessible via URL.
=> hide Comparison tools from sidebar

packages/server/webpack.config.js, yarn.lock
To fix webpack build error
```
ERROR in ./~/joi/lib/string.js
Module not found: Error: Can't resolve 'net' in '/home/fwd/Projects/Buffer/buffer-dev/buffer-analyze/node_modules/joi/lib'
@ ./~/joi/lib/string.js 3:10-24
@ ./~/joi/lib/index.js
@ ./~/jsonwebtoken/sign.js
@ ./~/jsonwebtoken/index.js
@ ./~/@bufferapp/app-sidebar/~/@bufferapp/session-manager/index.js
@ ./~/@bufferapp/app-sidebar/components/AppSidebar/index.jsx
@ ./~/@bufferapp/app-sidebar/index.js
@ ./packages/store/index.js
@ ./packages/web/index.jsx
@ multi (webpack)-dev-server/client?https://analyze.local.buffer.com:8080 webpack/hot/dev-server react-hot-loader/patch babel-polyfill ../web/index.jsx
ERROR in ./~/isemail/lib/isemail.js
Module not found: Error: Can't resolve 'dns' in …
```
=> fix webpack build

packages/audience-chart/components/AudienceChart/index.jsx, packages/report/__snapshots__/snapshot.test.js.snap, packages/report/components/ChartFactory/index.jsx, packages/report/package.json, packages/server/rpc/getReport/index.js, packages/server/rpc/getReport/index.test.js
To fix Instagram _Engagement and audience_ chart in reports, and prevent missing charts from breaking the reports.
=> Fix instagram audience chart report

packages/web/__snapshots__/snapshot.test.js.snap, packages/web/components/DefaultPage/index.jsx
To hide the Comparison link from users till we polished it
=> remove compare link from Dashboar welcome

packages/performance-tracking/middleware.js, packages/performance-tracking/middleware.test.js, packages/server/rpc/performanceTracking/index.js
To make sure performance tracking is not interfering with network performances.
**This sends out all the measures every 10 seconds**. I think this is a good balance between getting the data and making sure we are not interfering with the main RPC requests.
Given this interval, there is a chance we might lose some measures toward the end of the navigation, but for the cases, we are using the tracking at the moment I doubt this will be a concern, and we can always revisit the interval if needed :smile: .
=> Batch performance tracker RPC requests

packages/profile-loader/middleware.js, packages/profile-loader/middleware.test.js, packages/profile-loader/package.json, packages/server/rpc/profiles/index.js, packages/server/rpc/utils/profileParser.js
To display only social accounts enabled for Analyze.
Hey @tiggreen - ended up making a direct request to `get_social_accounts.json` to simplify the process for now. I feel that when this is more mature we'll just be able to move that endpoint from `web` to our API :)
=> Get Analyze-only social accounts

packages/report/middleware.js, packages/report/middleware.test.js, packages/server/rpc/getReport/index.js, packages/server/rpc/getReport/index.test.js
To reuse profile information fetched directly from the backend. This removes our need to reconcile information between the charts and local profile state.
=> get_report returns profile information for each chart

packages/audience-comparison-chart/reducer.js, packages/audience-comparison-chart/reducer.test.js, packages/comments-comparison-chart/reducer.js, packages/comments-comparison-chart/reducer.test.js, packages/engagement-comparison-chart/reducer.js, packages/engagement-comparison-chart/reducer.test.js, packages/likes-comparison-chart/reducer.js, packages/likes-comparison-chart/reducer.test.js, packages/reach-comparison-chart/reducer.js, packages/reach-comparison-chart/reducer.test.js, packages/shared-components/ComparisonChart/chartConfig.jsx, packages/shared-components/ComparisonChart/index.jsx
Comparison charts should only stop loading when their metric has been fetched. This also tweaks the way we generate the `highchartsConfig` for these charts to prevent race conditions and state overwriting between charts.
=> Fix comparison state inconsistencies in loading states and navigating back and forth to the comparison tool

packages/contextual-compare/__snapshots__/snapshot.test.js.snap, packages/contextual-compare/components/PresetsDropdown/List.jsx
To ensure tooltips appear, I've moved the whole HelpButton to be a sibling of the preset button, since some browsers don't play nicely with different hover events inside a Button :)
=> Fix contextual tooltip hover on Firefox

packages/audience-comparison-chart/mocks/dailyData.js, packages/comments-comparison-chart/mocks/dailyData.js, packages/engagement-comparison-chart/mocks/dailyData.js, packages/likes-comparison-chart/mocks/dailyData.js, packages/reach-comparison-chart/mocks/dailyData.js, packages/server/rpc/comparison/index.js, packages/server/rpc/comparison/mockResponse.js, packages/shared-components/ComparisonChart/chartConfig.jsx, packages/shared-components/ComparisonChart/index.jsx, packages/shared-components/ComparisonChart/story.jsx, packages/shared-components/ComparisonChartTooltip/index.jsx, packages/shared-components/ComparisonChartTooltip/story.jsx, packages/shared-components/ComparisonChartWrapper/index.jsx, packages/shared-components/__snapshots__/snapshot.test.js.snap
To show the data for all the selected profiles in the Comparison Chart tooltip.
BAN-68
Similar to what we are doing in the footer, we are now using the `profiles` collection to extrapolate the profiles data.
=> Comparisons Charts multi profiles tool-tip 

packages/report/middleware.js, packages/report/middleware.test.js
Always trigger a report fetch on `SET_DATE_RANGE`, do not trigger it on `LOCATION_CHANGE` when loading the export view
Fixes BAN-132
=> Fix report export not selecting current date ranges

packages/server/rpc/compare/metricsConfig.js, packages/server/rpc/summary/index.js, packages/server/rpc/summary/index.test.js
The goal of this PR is to change Post Clicks label to Link Clicks in FB summary and compare charts. We have been pulling the actual link clicks metrics from backend and we just needed to adjust the label. 
=> Facebook Insights: Change Post Clicks to Link Clicks

packages/compare-chart/__snapshots__/snapshot.test.js.snap, packages/comparison_chart/__snapshots__/snapshot.test.js.snap, packages/posts-summary-table/__snapshots__/snapshot.test.js.snap, packages/report/__snapshots__/snapshot.test.js.snap, packages/server/rpc/postsSummary/index.js, packages/server/rpc/postsSummary/index.test.js, packages/server/rpc/postsSummary/mockResponses.js, packages/shared-components/GridItem/index.jsx, packages/shared-components/__snapshots__/snapshot.test.js.snap, packages/summary-table/__snapshots__/snapshot.test.js.snap
- Bottom right metric of Performance Table and Posts table is misaligned/offset to the right
- Order of metrics in Performance table and Posts table should be the same
=> Fix small metrics table bugs BAN-146 BAN-147

packages/comparison_chart/__snapshots__/snapshot.test.js.snap, packages/comparison_chart/components/ChartTooltip/index.jsx, packages/server/rpc/comparison/index.js
On all charts where there were no posts published, let's change the copy from "no post published for buffer" to "No posts were published for buffer"
On the engagement chart, let's pluralize "engagement": Update from "123 engagement for buffer" to "123 engagements for buffer"
=> Task/comparisons tooltip BAN-140

packages/date-picker/index.js, packages/web/components/ReportsPage/index.jsx
Date picker is waiting for an "analytics_start_date" call to finish, when comparisons does not need that. Comparisons can use `staticData` and reports does not need it anymore as reports have date ranges associated now.
=> Fix date picker loading endlessly when loading comparisons

packages/date-picker/index.js, packages/date-picker/index.test.jsx, packages/date-picker/reducer.js, packages/date-picker/reducer.test.js, packages/report/__snapshots__/snapshot.test.js.snap, packages/report/components/DateRange/index.jsx, packages/report/components/DateRange/story.jsx, packages/report/components/Report/story.jsx, packages/server/rpc/audience/index.js, packages/server/rpc/audience/index.test.js, packages/server/rpc/average/index.js, packages/server/rpc/average/index.test.js, packages/server/rpc/compare/index.js, packages/server/rpc/compare/index.test.js, packages/server/rpc/comparison/index.js, packages/server/rpc/comparison/index.test.js, packages/server/rpc/contextual/index.js, packages/server/rpc/contextual/index.test.js, packages/server/rpc/getReport/index.js, packages/server/rpc/getReport/index.test.js, packages/server/rpc/posts/index.js, packages/server/rpc/posts/index.test.js, packages/server/rpc/postsSummary/index.js, packages/server/rpc/postsSummary/index.test.js, packages/server/rpc/summary/index.js, packages/server/rpc/summary/index.test.js, packages/server/rpc/topPosts/index.js, packages/server/rpc/topPosts/index.test.js
Fixes a bug where positive UTC offset was pushing the date range back by one day
This moves the conversion of the dates (from unix timestamp to `MM/DD/YYYY') from the RPC endpoint to the client, therefore ensuring that we are always converting the dates based on the client timezone.
Bonus with this is that RPC requests match the API endpoint format, and are also easier to read.
As we have a few reports already using the custom date this is adding
support for both date formats. We will remove this once we have
migrated all the reports to the new format.
=> Fix day offset with positive UTC offset (BAN-144)

packages/report/PDFFormatter.js, packages/report/PDFFormatter.test.js, packages/report/middleware.js, packages/report/middleware.test.js
To remove a blank page appearing at the end of exported PDFs when the PDF has only one page.
=> Remove extra blank page in PDFs

packages/hourly-chart/__snapshots__/snapshot.test.js.snap, packages/hourly-chart/components/Legend/index.jsx
To make the Hourly chart more consistent with the current style for other charts by having its legend with circle labels rather than square ones.
=> [BAN-183] Make Hourly Chart labels round to match other charts

packages/report/PDFFormatter.js, packages/report/__snapshots__/snapshot.test.js.snap, packages/report/components/ChartFactory/index.jsx
To ensure we use as much space available as possible per page so that there are no big chunks of whitespace lying between charts.
=> Fix chart spacing on PDF export

packages/server/rpc/compare/index.js, packages/server/rpc/compare/index.test.js
Follower counts on the Metrics Breakdown chart was wrong when selecting "Total period": it was displayed as a sum of the current daily value + all the previous days, where in this case it should always be the daily value.
=> [BAN-187] Store only current value for followers on total period

packages/compare-chart/__snapshots__/snapshot.test.js.snap, packages/compare-chart/components/CompareChart/index.jsx, packages/compare-chart/components/CompareChart/story.jsx
The loading and empty state weren't vertically centered on the Metrics Breakdown graph. This PR fixes it :)
=> [ANA-128] Ensure loading and empty state is centered on Metrics Breakdown graph

packages/contextual-compare/__snapshots__/snapshot.test.js.snap, packages/contextual-compare/components/Title/index.jsx, packages/contextual-compare/components/Title/story.jsx, packages/hourly-chart/__snapshots__/snapshot.test.js.snap
To ensure we're giving as much context on the answer they've persisted on a report by saving a contextual chart with a preset selected, the title for the chart will be the question selected in the dropdown, or "Engagements & Audience" if a custom combination was selected.
=> [ANA-205] Add more meaningful titles for Contextual charts con reports

packages/compare-chart/__snapshots__/snapshot.test.js.snap, packages/compare-chart/components/ChartTooltip/index.jsx, packages/compare-chart/components/ChartTooltip/story.jsx, packages/server/rpc/compare/index.js, packages/server/rpc/compare/metricsConfig.js
To show Engagement Rate for Instagram in the Metrics Breakdown chart
=> Show Engagement rate for IG on Metrics Breakdown Chart ANA-198

packages/posts-table/__snapshots__/snapshot.test.js.snap, packages/posts-table/components/PostsTable/metrics.js, packages/server/rpc/postsSummary/index.js
Display posts engagement rate, and add sort by engagement rate, in Instagram posts tab
=> show Engagement rate on Instagram posts ANA-198

packages/server/rpc/compare/metricsConfig.js
To show the following metrics in Instagram Metrics Breakdown Chart:
- Posts
- Impressions
- Reach
- Post Likes
- Post Comments
- Post Saves
- Video Views
- New Followers
- Total Followers
- Engagement Rate
=> Add new metrics to Instagram Metrics Breakdown Chart (ANA-154)

packages/server/rpc/compare/index.js, packages/server/rpc/compare/index.test.js, packages/server/rpc/compare/metricsConfig.js
Engagement Rate = `page_story_adds` / `page_posts_impressions`. 
=> Add Facebook engagement rate metric to FB compare chart ANA-122

packages/posts-table/__snapshots__/snapshot.test.js.snap, packages/posts-table/components/PostsTable/metrics.js, packages/server/rpc/postsSummary/index.js, packages/server/rpc/postsSummary/index.test.js, packages/server/rpc/postsSummary/mockResponses.js
We should display engagement rate metric on FB "Post Summary" and "Post Breakdown" tables.
=> Add engagement rate to Facebook posts tab (summary and post breakdown) ANA-122

packages/posts-table/__snapshots__/snapshot.test.js.snap, packages/posts-table/components/PostsTable/metrics.js
To add Engagement and Impressions metrics in Instagram Posts Table
The visible metrics are now:
- Likes
- Comments
- Post Impressions
- Post Reach
- Engagement Rate 
This also:
- move Engagement Rate metrics into the Audience column for Facebook
- rename Post Impressions and Post Reach label for Twitter so that they enter in one line 
=>  Add engagement and impressions in Instagram PostsTable (ana-159)

packages/server/package.json, yarn.lock
=> update moment-timezone to 0.5.16

packages/server/rpc/postsSummary/index.js, packages/server/rpc/postsSummary/index.test.js
- replace Impressions with Engagement Rate to Twitter Posts Summary
- remove Impressions from Facebook Posts summary to bring it to 6 metrics
=> Posts Summary Metrics (ANA-197)

packages/server/package.json, packages/store/index.js, packages/store/package.json, yarn.lock
To fix action tracking :smile: 
=> update buffermetrics to 0.5.2

packages/nav-sidebar/__snapshots__/snapshot.test.js.snap, packages/nav-sidebar/components/Insights.jsx, packages/web/__snapshots__/snapshot.test.js.snap, packages/web/components/AnswersTab/index.jsx, packages/web/components/AnswersTab/index.test.jsx, packages/web/components/InsightsPage/index.jsx, packages/web/components/OverviewTab/index.jsx
To move the Engagement and Audience charts out of the Overview tab and
into a dedicated section called Answers.
=> add Answers tab (ANA-202)

packages/server/index.js, packages/server/rpc/audience/index.js, packages/server/rpc/audience/index.test.js, packages/server/rpc/average/index.js, packages/server/rpc/average/index.test.js, packages/server/rpc/compare/index.js, packages/server/rpc/compare/index.test.js, packages/server/rpc/comparison/index.js, packages/server/rpc/comparison/index.test.js, packages/server/rpc/contextual/index.js, packages/server/rpc/contextual/index.test.js, packages/server/rpc/getReport/index.js, packages/server/rpc/getReport/index.test.js, packages/server/rpc/summary/index.js, packages/server/rpc/summary/index.test.js
To point Analyze API to a staging environment.
To override Analyze API address you need to set `ANALYZE-API-ADDR` headers to the expected url.
On Chrome you can use [modeHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) to set that :smile:.
It overrides the url for the following endpoints:
- rpc/compare
- rpc/report
- rpc/summary
- rpc/contextual
- rpc/comparison
- rpc/audience
- rpc/average
=> Add support for staging Analyze API

packages/server/rpc/compare/index.js, packages/server/rpc/compare/index.test.js, packages/server/rpc/compare/mockResponses.js
To save two requests and ensure that the total always matches the values in the charts.
It also fixes `engagement_rate` and `comments` totals for Facebook.
=> rpc/compare use daily_totals to compute totals [ANA-232] [ANA-242]

packages/server/rpc/compare/index.js, packages/server/rpc/compare/index.test.js, packages/server/rpc/compare/mockResponses.js
To fix the previous period total calculation for averaged metrics.
=> fix compare previous averaged totals calculation

packages/server/rpc/postsSummary/index.js, packages/server/rpc/postsSummary/index.test.js
The backend PR is coming soon. I've separated posts summary total endpoint from totals endpoint that calculates the total for the performance table. 
=> [ANA-241] Use the new RPC endpoint for post summary table.

packages/server/rpc/compare/metricsConfig.js
=> [ANA-239] Total fans should be the default metric for IG Metrics Breakdown chart.

buffer-analyze/templates/deployment.yaml
=> Fix helm deployment file to use the last image tag

packages/pdf-export/middleware.js, packages/pdf-export/middleware.test.js, packages/server/index.js
To prevent special characters in the report name from breaking pdf export.
fixes https://app.bugsnag.com/buffer/buffer-analyze/errors/5b2b9f7206cee70018e74698?event_id=5b2b9f7206cee70018e74697&i=sk&m=nw
=> ensure encoded URL in Lamba headers (ANA-252)

packages/posts-table/__snapshots__/snapshot.test.js.snap, packages/posts-table/components/PostsTable/components/PostItem/index.jsx, packages/posts-table/components/PostsTable/index.jsx, packages/report/PDFFormatter.js, packages/report/PDFFormatter.test.js, packages/report/mocks/reportWithTable.js
To fix reports pagination for Posts Tables
This was a fun bug to track down :smile: .
The new layout was breaking the page break calculations and that was an easy fix, but then I realized that even though the calculations were working fine, the pdf was ignoring the `page-break-before` rules. Turned out rendering to pdf is ignoring page breaks for `table`; therefore I've changed the markup a bit and we are now using ordered lists.
I've added in a test to make sure the page break logic is working fine with this new layout, but that is still a bit brittle, as it's testing against a mocked layout. :thinking: It could be worth exploring some integrations tests for the export, as it's quite coupled with the actual components layouts and i think this is not the first time this is breaking cause …
=> fix page break for posts table

packages/report/PDFFormatter.js, packages/report/PDFFormatter.test.js, packages/report/mocks/reportWithTable.js
If we need to push the first element of a list to a new page, we rather break before the Section title.
=> send entire list on new page if first li too big

packages/compare-chart/__snapshots__/snapshot.test.js.snap, packages/compare-chart/components/Footer/index.jsx, packages/hourly-chart/__snapshots__/snapshot.test.js.snap, packages/hourly-chart/components/HourlyEngagementChart/index.jsx, packages/hourly-chart/components/Legend/index.jsx, packages/report/__snapshots__/snapshot.test.js.snap, packages/report/components/ChartFactory/index.jsx, packages/report/components/Cover/index.jsx, packages/report/components/Cover/story.jsx, packages/report/components/DateRange/index.jsx, packages/report/components/DateRange/story.jsx, packages/report/components/Report/index.jsx, packages/report/components/Report/story.jsx, packages/web/__snapshots__/snapshot.test.js.snap
This pull request is just for adding the cover page for reports when exporting. It doesn't have all the other report features (like consistent header and footer etc). I've tried quite a few different variations for the cover page and it seems the centralised title and date works best for reports with images. I'm sure there is more we can do but it could be good to get it out there and see what people say. Though I'm aware it's not the most exciting cover page right now! Maybe we can do things like colour tinting and such in the near future.
Be great to get your eyes on this @federicoweber 👍 As for the review, on speaking with Mike he mentioned that we shouldn't worry too much when the test coverage is failing on `story.jsx` files. Aside from this, the code should be pretty simple. The …
=> Add cover page for reports when exporting

packages/audience-chart/__snapshots__/snapshot.test.js.snap, packages/average-table/__snapshots__/snapshot.test.js.snap, packages/compare-chart/__snapshots__/snapshot.test.js.snap, packages/comparison_chart/__snapshots__/snapshot.test.js.snap, packages/contextual-compare/__snapshots__/snapshot.test.js.snap, packages/hourly-chart/__snapshots__/snapshot.test.js.snap, packages/posts-summary-table/__snapshots__/snapshot.test.js.snap, packages/posts-table/__snapshots__/snapshot.test.js.snap, packages/profile-overview/__snapshots__/snapshot.test.js.snap, packages/report/__snapshots__/snapshot.test.js.snap, packages/report/components/Cover/index.jsx, packages/report/components/Cover/story.jsx, packages/report/components/DateRange/index.jsx, packages/report/components/EditTitle/index.jsx, packages/report/components/Report/index.jsx, packages/shared-components/ChartTitle/index.jsx, packages/summary-table/__snapshots__/snapshot.test.js.snap, packages/web/__snapshots__/snapshot.test.js.snap
This contains a few visual updates to the reports cover page. Things were looking a little hectic and it needed calming down a bit visually. I've rebalanced a few of the weights and sizes in the reports and in the chart headers so everything feels a little more consistent from the graphs to the reports to the PDF export.
I was able to remove some code that didn't seem needed anymore as the chart headers for app and reports is now the same :)
This repo is CI/CD enabled and staging deployment should be available at:
https://better-report-cover-analyze.dev.buffer.com/ :smile:
=> Report cover updates

packages/early-access-check/middleware.js, packages/early-access-check/middleware.test.js
Instead of checking to see if the user has `analyze_early_access` feature flip we can simply check if the user has any analyze enabled profiles or not. 
This PR will be merged after we ran the mongo script that will disable all analyze active profiles that don't have analyze subscriptions anymore. 
=> [ANA-312] Tweak analyze early access to be based on enabled profiles

packages/account/.babelrc, packages/account/README.md, packages/account/index.js, packages/account/index.test.jsx, packages/account/middleware.js, packages/account/middleware.test.js, packages/account/package.json, packages/account/reducer.js, packages/account/reducer.test.js, packages/nav-sidebar/__snapshots__/snapshot.test.js.snap, packages/nav-sidebar/components/FeedbackLink.jsx, packages/nav-sidebar/components/Label.jsx, packages/nav-sidebar/components/NavSidebar.jsx, packages/nav-sidebar/components/TrialStatus.jsx, packages/nav-sidebar/components/story.jsx, packages/nav-sidebar/index.js, packages/nav-sidebar/index.test.jsx, packages/nav-sidebar/package.json, packages/profile-selector/reducer.js, packages/profile-selector/reducer.test.js, packages/server/rpc/getAccountDetails/index.js, packages/server/rpc/getAccountDetails/test.js, packages/server/rpc/index.js, packages/store/index.js, packages/store/package.json, packages/store/reducers.js, packages/web/__snapshots__/snapshot.test.js.snap, yarn.lock
To provide the trial status on the nav sidebar for Analyze. The status is displayed only for owners right now, as that's data that's only available for them. Once I merge and deploy https://github.com/bufferapp/buffer-web/pull/15382, it will become available for all team members too!
There is also a piece of code that wraps the trial status on a `Link` component that will become available only for the owner. For now, that's hardcoded to `false` in the profiles reducer, but I will create another PR that will return that information from the profiles endpoint on the API as well (whether the user requesting the profiles for the organization is the owner or not), and will tweak the reducer & RPC accordingly :)
=> Trial status on sidebar

packages/profile-overview/__snapshots__/snapshot.test.js.snap, packages/shared-components/GridItem/story.jsx, packages/shared-components/TruncatedNumber/index.jsx, packages/shared-components/__snapshots__/snapshot.test.js.snap
To ease understanding of engagement rate changes by showing decimals if the value is < 10.
=> show decimals in charts footer if % < 10 (ANA-328)

packages/server/rpc/profiles/index.js, packages/server/rpc/profiles/index.test.js
To properly sort profiles in the selectors
=> Alphabetically sort profiles in the selector

packages/report/components/ChartFactory/index.jsx
To fix Hourly Chart rendering in reports.
Expanding the state was creating an error in the Hourly chart in reports as the SelectedMetric is going to be overridden with by a string. And actually is not needed because we are passing that down from the RPC endpoint. Not sure why it wasn't properly doing that when I was testing the hashtag table :confused:.
=> fixes reports state error
